[[block]]
block = "music"
format = "{$icon $combo.str(max_w:25,rot_interval:0.5) $play $prev $next $player.str(max_w:5,rot_interval:0.5) [$cur/$avail]|}"

[[block]]
block = "memory"
format = "$icon $mem_used_percents"
format_alt = "$icon $swap_used_percents (swap)"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
format = "$icon $1m"
interval = 1

[[block]]
block = "net"
format = "$icon {$signal_strength $ssid.str(max_w:5,rot_interval:0.5)|}"
format_alt = "$icon {$signal_strength $ssid.str(max_w:5,rot_interval:0.5) $frequency|} ipv4-$ip ipv6-$ipv6 via $device"

[[block]]
block = "backlight"

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
format = "$icon $percentage {$time|}"

[[block]]
block = "sound"
format = "$icon {$volume.bar(v:true) $volume.eng(w:2)|}"
headphones_indicator = true

[[block.click]]
button = "left"
cmd = "pwvucontrol"

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%F %R')"
interval = 60

[icons]
icons = "material-nf"

[theme]
theme = "gruvbox-dark"
