switch:
    home-manager --flake . switch

bootstrap:
    nix run --extra-experimental-features "nix-command flakes" --no-write-lock-file github:nix-community/home-manager/ -- --extra-experimental-features "nix-command flakes" --flake . switch

gc:
    home-manager expire-generations -7days
    nix store gc
