directory: ~/Music
library: ~/Music/library.db
import:
  move: yes
  write: yes
plugins: [edit, fetchart, chroma, thumbnails, replaygain, mbsync, fuzzy, duplicates, badfiles]
replaygain:
  auto: no
  backend: ffmpeg
asciify_paths: yes
